### ISSUE TITLE
스터디 리스트 페이지

### ISSUE THREAD

**Issue by choify** [Team-Do-Nothing/swithme-frontend#2]
## 1. 구현할 기능

- 스터디 리스트 뷰 구현
- 페이징 기능 추가
- 검색 기능 구현
- 필터 및 정렬 기능 구현
- api 적용

## 2. 상세작업 내용

- [x] 스터디 리스트 뷰 구현
- [x] 페이징 기능 추가
- [x] 검색 기능 구현
- [x] 필터 및 정렬 기능 구현

## 📄 참고 사항
- 스터디 리스트 페이지를 구현

## 관련 이슈 (연관된 스토리 이슈 번호를 링크)
-  #3 
- #6 
- #7 
- #8 

## ⏰ 예상 소요 기간
~ 2023.10.08
