### ISSUE TITLE
스터디 목록 페이지 반응형으로 변경

### ISSUE THREAD

**Issue by choify** [Team-Do-Nothing/swithme-frontend#28]
## 1. 구현할 기능
- 페이지 스타일 변경
- 카드 컴포넌트 스타일 변경
- 카드 검색 컴포넌트 스타일 변경
- 필터버튼 컴포넌트 스타일 변경

## 2. 상세 작업 내용

- [x] 페이지 스타일 변경
- [x] 카드 컴포넌트 스타일 변경
- [x] 카드 검색 컴포넌트 스타일 변경
- [x] 필터버튼 컴포넌트 스타일 변경
