### ISSUE TITLE
[내 스터디] 페이지 기본 구조 구현

### ISSUE THREAD

**Issue by choify** [Team-Do-Nothing/swithme-frontend#32]
## 1. 구현할 기능
- 내 스터디 각 페이지(공지,게시판,멤버,챌린지,일정) 생성
- 내 스터디 네비게이션 컴포넌트 구현
- 내 스터디 공지 페이지 기본 구조 구현
- 내 스터디 게시판 페이지 기본 구조 구현
- 내 스터디  멤버 페이지 기본 구조 구현
- 내 스터디 챌린지 페이지 기본 구조 구현
- 내 스터디 일정 페이지 기본 구조 구현

## 2. 상세 작업 내용
- [x] 내 스터디 각 페이지(메인,공지,게시판,멤버,챌린지,일정) 생성
- [x] 내 스터디 네비게이션 컴포넌트 구현
- [x] 내 스터디 공지 페이지 기본 구조 구현
- [x] 내 스터디 게시판 페이지 기본 구조 구현
- [x] 내 스터디  멤버 페이지 기본 구조 구현
- [x] 내 스터디 챌린지 페이지 기본 구조 구현
- [x] 내 스터디 일정 페이지 기본 구조 구현

## 📄 이슈 링크
- #33 
- #40
- #41
- #42
- #43
- #44
- #45
