### ISSUE TITLE
[내 스터디] 공지사항 페이지 구현

### ISSUE THREAD

**Issue by choify** [Team-Do-Nothing/swithme-frontend#46]
## 1. 구현할 기능
- 공지사항 게시글 카드 컴포넌트 제작
- 공지사항 게시글 클릭 시 게시글 페이지로 이동
- 공지사항 게시글 페이지 제작
- 공지사항 더미 데이터 제작
- 더미 데이터 연결

## 2. 상세 작업 내용
- [x] 공지사항 게시글 카드 컴포넌트 제작
- [x] 공지사항 게시글 클릭 시 게시글 페이지로 이동
- [x] 공지사항 게시글 페이지 제작
- [x] 공지사항 더미 데이터 제작
- [x] 더미 데이터 연결

## 3. 관련 이슈
- #47
- #48
- #49
